### ISSUE TITLE
Update to  work in arch

### ISSUE THREAD

**Issue by landerson78** [llelectronics/3ncode#12]
Wont install in arch due to python2-dbus has been depreciated to dbus-python and  need python2-dbus for
Could not find all required packages:
	python2-dbus (Wanted by: 3ncode-git -> python2-pyqt4)
	python2-dbus (Wanted by: 3ncode-git -> python2-pyqt4 -> pyqt4-common)

**Comment by llelectronics** [comment]
Yes I am working on it in the kirigami branch already. This will switch to python3 and fix some other issues. I just need time to work on it. Feel free to give me PRs

**Comment by landerson78** [comment]
k ty I love the app it is awesome I have used it for a over a year till it quit working for me around a year ago. ty for all the hard work.

**Comment by llelectronics** [comment]
See: https://github.com/NeptuneOS/3ncode/tree/kirigami_app 

I updated it to kirigami and python3 support
