### ISSUE TITLE
3ncode  not working after python update.

### ISSUE THREAD

**Issue by Saber78** [llelectronics/3ncode#3]
file:///usr/share/3ncode/3ncode.qml:35:1: module "org.kde.plasma.components" is not installed 
     import org.kde.plasma.components 0.1 as PlasmaComponents 
     ^ 
Traceback (most recent call last):
  File "./encode.py", line 147, in <module>
    rootObject.openFile.connect(openFile)
AttributeError: 'NoneType' object has no attribute 'openFile'

error i get and 3ncode wont open

**Comment by Saber78** [comment]
I have fig out what is messing it up is upgrading kdebase-runtime (16.08.3-1 -> 16.08.3-3) I had to downgrade to get it to run again. Not sure if its a issue with there code or your code.

**Comment by llelectronics** [comment]
As the version number of upstream 16.08.3 is the same and only the packaging -1 to -3 changed I think it is a packaging error.

**Comment by Saber78** [comment]
k. ty for the wonderful program.
